/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import codigo.Funciones;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author valer
 */
public class ad_provincia extends javax.swing.JFrame {

    /**
     * Creates new form ad_provincia
     */
    public ad_provincia() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);//cuando se cierra la ventana se acabe el programa
        setTitle("SIGEB | Provincia"); //Poner el título
        //this.setLocation(500,100); //posición inicial de la ventana. Pongo lo que yo quiero
        this.setLocationRelativeTo(null);
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void insertarProvincias()
    {
        //Añadir provincias en un combo box
        Funciones fun = new Funciones();
        ArrayList al = new ArrayList();
        al = fun.nombreProvincias();
        
        Iterator it = al.iterator();
        while(it.hasNext())
        {
            ad_jCB_eliminarProv.addItem(it.next().toString());
        }    
        
    } 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ad_jCB_eliminarPro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        ad_jL_textElim = new javax.swing.JLabel();
        ad_jCB_eliminarProv = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        ad_jtb_agregar = new javax.swing.JToggleButton();
        ad_jtb_eliminar = new javax.swing.JToggleButton();
        ad_jtb_regresar = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        ad_jTF_nombr = new javax.swing.JTextField();
        ad_jL_textEscrib = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ad_jCB_eliminarPro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ad_jCB_eliminarPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eliminar Provincia", "Añadir Provincia" }));
        ad_jCB_eliminarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_jCB_eliminarProActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Seleccione la acción a realizar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(ad_jCB_eliminarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_jCB_eliminarPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ad_jL_textElim.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ad_jL_textElim.setText("Seleccione la provincia a eliminar:");

        ad_jCB_eliminarProv.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ad_jL_textElim)
                .addGap(18, 18, 18)
                .addComponent(ad_jCB_eliminarProv, 0, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ad_jCB_eliminarProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ad_jL_textElim))
        );

        ad_jtb_agregar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ad_jtb_agregar.setText("Agregar");

        ad_jtb_eliminar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ad_jtb_eliminar.setText("Eliminar");

        ad_jtb_regresar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ad_jtb_regresar.setText("Regresar");
        ad_jtb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_jtb_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ad_jtb_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ad_jtb_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ad_jtb_regresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_jtb_agregar)
                    .addComponent(ad_jtb_regresar)
                    .addComponent(ad_jtb_eliminar))
                .addContainerGap())
        );

        ad_jTF_nombr.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        ad_jL_textEscrib.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ad_jL_textEscrib.setText("Escriba el nombre de la provincia:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ad_jL_textEscrib)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(ad_jTF_nombr, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_jTF_nombr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ad_jL_textEscrib)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void inicializar()
    {
        ad_jL_textEscrib.setEnabled(false);
        ad_jTF_nombr.setEnabled(false);
        ad_jtb_agregar.setEnabled(false);
        ad_jCB_eliminarProv.setEnabled(false);
        ad_jL_textElim.setEnabled(false);
        ad_jtb_eliminar.setEnabled(false);
    }
    private void ad_jCB_eliminarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_jCB_eliminarProActionPerformed
        // TODO add your handling code here:
        if (ad_jCB_eliminarPro.getSelectedIndex() == 0)
        {
            //eliminar provincia
            ad_jL_textEscrib.setVisible(false);
            ad_jTF_nombr.setVisible(false);
            ad_jtb_agregar.setVisible(false);
            ad_jL_textElim.setVisible(true);
            ad_jCB_eliminarProv.setVisible(true);
            ad_jtb_eliminar.setVisible(true);
            
            ad_jL_textElim.setEnabled(true);
            ad_jCB_eliminarProv.setEnabled(true);
            ad_jtb_eliminar.setEnabled(true);
            
            insertarProvincias();
            
            
        }
        else
        { 
            //añadir provincia
            ad_jL_textEscrib.setVisible(true);
            ad_jTF_nombr.setVisible(true);
            ad_jtb_agregar.setVisible(true);
            ad_jCB_eliminarProv.setVisible(false);
            ad_jL_textElim.setVisible(false);
            ad_jtb_eliminar.setVisible(false);
            
            ad_jL_textEscrib.setEnabled(true);
            ad_jTF_nombr.setEnabled(true);
            ad_jtb_agregar.setEnabled(true);
        }
    }//GEN-LAST:event_ad_jCB_eliminarProActionPerformed

    private void ad_jtb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_jtb_regresarActionPerformed
        // TODO add your handling code here:
        menPrinci mp = new menPrinci();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ad_jtb_regresarActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ad_provincia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ad_provincia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ad_provincia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ad_provincia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ad_provincia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ad_jCB_eliminarPro;
    private javax.swing.JComboBox<String> ad_jCB_eliminarProv;
    private javax.swing.JLabel ad_jL_textElim;
    private javax.swing.JLabel ad_jL_textEscrib;
    private javax.swing.JTextField ad_jTF_nombr;
    private javax.swing.JToggleButton ad_jtb_agregar;
    private javax.swing.JToggleButton ad_jtb_eliminar;
    private javax.swing.JToggleButton ad_jtb_regresar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
