/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import codigo.Funciones;
import conexion.Procedimientos;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author valer
 */
public class cl_registrar extends javax.swing.JFrame {

    private boolean bandera;
    static ResultSet res;
    int cont;
    /**
     * Creates new form cl_registrar
     */
    public cl_registrar(int valor) {
        initComponents();
        //this.setSize(466, 643); //ancho y largo de la ventana
        this.setLocationRelativeTo(null); 
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);//cuando se cierra la ventana se acabe el programa
        inicializar(valor);
        insertarProvincias();
        bandera = false;
        //this.setLocation(500,100); //posición inicial de la ventana. Pongo lo que yo quiero
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cl_jL_registroCliente = new javax.swing.JLabel();
        cl_jL_actualizarCliente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cl_jTF_nombreEmpresa = new javax.swing.JTextField();
        cl_jTF_nombreRepresentante = new javax.swing.JTextField();
        cl_jTF_ruc = new javax.swing.JTextField();
        cl_jTF_telefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cl_jCB_estado = new javax.swing.JComboBox<>();
        cl_jTF_telefonocelular = new javax.swing.JTextField();
        cl_jL_telefonoCelular = new javax.swing.JLabel();
        cl_jTF_apellidosRepresentante = new javax.swing.JTextField();
        cl_jL_apellidoRepresentate = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cl_jCB_provincia = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cl_jTF_ciudad = new javax.swing.JTextField();
        cl_jTF_parroquia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        cl_jB_registrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cl_jTB_actualizar = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        cl_jL_registroCliente.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cl_jL_registroCliente.setText("Registrar cliente");

        cl_jL_actualizarCliente.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cl_jL_actualizarCliente.setText("Actualizar cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cl_jL_registroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cl_jL_actualizarCliente)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jL_registroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cl_jL_actualizarCliente))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 460, 50);

        cl_jTF_nombreEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cl_jTF_nombreEmpresaFocusLost(evt);
            }
        });
        cl_jTF_nombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_jTF_nombreEmpresaActionPerformed(evt);
            }
        });
        cl_jTF_nombreEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cl_jTF_nombreEmpresaKeyReleased(evt);
            }
        });

        cl_jTF_nombreRepresentante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cl_jTF_nombreRepresentanteFocusLost(evt);
            }
        });
        cl_jTF_nombreRepresentante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cl_jTF_nombreRepresentanteKeyReleased(evt);
            }
        });

        cl_jTF_ruc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cl_jTF_rucFocusLost(evt);
            }
        });
        cl_jTF_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cl_jTF_rucKeyReleased(evt);
            }
        });

        cl_jTF_telefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cl_jTF_telefonoFocusLost(evt);
            }
        });
        cl_jTF_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cl_jTF_telefonoKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Nombre Empresa:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Nombres representante:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("RUC:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Teléfono convencional:");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Estado:");

        cl_jCB_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cl_jCB_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_jCB_estadoActionPerformed(evt);
            }
        });

        cl_jTF_telefonocelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cl_jTF_telefonocelularFocusLost(evt);
            }
        });
        cl_jTF_telefonocelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cl_jTF_telefonocelularKeyReleased(evt);
            }
        });

        cl_jL_telefonoCelular.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cl_jL_telefonoCelular.setText("Teléfono celular:");

        cl_jTF_apellidosRepresentante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cl_jTF_apellidosRepresentanteFocusLost(evt);
            }
        });
        cl_jTF_apellidosRepresentante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cl_jTF_apellidosRepresentanteKeyReleased(evt);
            }
        });

        cl_jL_apellidoRepresentate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cl_jL_apellidoRepresentate.setText("Apellidos representante:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(cl_jL_telefonoCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cl_jTF_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(cl_jCB_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cl_jTF_telefonocelular, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cl_jL_apellidoRepresentate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cl_jTF_nombreEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cl_jTF_nombreRepresentante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cl_jTF_apellidosRepresentante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cl_jTF_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jTF_nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jTF_nombreRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jL_apellidoRepresentate)
                    .addComponent(cl_jTF_apellidosRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jTF_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jTF_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jTF_telefonocelular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_jL_telefonoCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jCB_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(141, 141, 141))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 110, 390, 280);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Dirección");

        cl_jCB_provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_jCB_provinciaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Provincia:");

        cl_jTF_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_jTF_ciudadActionPerformed(evt);
            }
        });
        cl_jTF_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cl_jTF_ciudadKeyReleased(evt);
            }
        });

        cl_jTF_parroquia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cl_jTF_parroquiaKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setText("Ciudad:");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setText("Parroquia:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 108, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cl_jTF_ciudad)
                            .addComponent(cl_jCB_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cl_jTF_parroquia)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jCB_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jTF_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_jTF_parroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(50, 380, 370, 180);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setText("Datos Personales");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 70, 140, 23);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(80, 312, 300, 0);

        cl_jB_registrar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cl_jB_registrar.setText("Registrar");
        cl_jB_registrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cl_jB_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_jB_registrarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cl_jTB_actualizar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cl_jTB_actualizar.setText("Actualizar");
        cl_jTB_actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(cl_jB_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cl_jTB_actualizar)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_jTB_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_jB_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(40, 550, 390, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void inicializar(int valor)
    {
        //1 --> registrar
        //2 --> actualizar
        switch (valor)
        {
            case 1:
                setTitle("SIGEB | Registro Clientes"); //Poner el título
                this.cl_jL_actualizarCliente.setVisible(false);
                this.cl_jTB_actualizar.setVisible(false);
                this.cl_jCB_estado.setSelectedIndex(0);
                this.cl_jCB_estado.setEnabled(false);
                break;
            case 2:
                setTitle("SIGEB | Actualización Cliente");
                this.cl_jL_registroCliente.setVisible(false);
                this.cl_jL_actualizarCliente.setVisible(true);
                
                this.cl_jTF_nombreEmpresa.setEditable(false);
                this.cl_jTF_nombreRepresentante.setEditable(false);
                this.cl_jTF_ruc.setEditable(false);
                this.cl_jTF_apellidosRepresentante.setEditable(false);
                this.cl_jB_registrar.setVisible(false);
                this.cl_jCB_estado.setEnabled(false);
                break;
        
        }
    }
    
    private void insertarProvincias()
    {
        //Añadir provincias en un combo box
        Funciones fun = new Funciones();
        ArrayList al = new ArrayList();
        al = fun.nombreProvincias();
        
        Iterator it = al.iterator();
        while(it.hasNext())
        {
            cl_jCB_provincia.addItem(it.next().toString());
        }    
        
    }        
    private void cl_jTF_nombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_jTF_nombreEmpresaActionPerformed
        // TODO add your handling code here:
        String valor =cl_jTF_nombreEmpresa.getText();
        System.out.println("valor"+ valor);
        System.out.println("valor"+ valor.length());
        
    }//GEN-LAST:event_cl_jTF_nombreEmpresaActionPerformed

    private void cl_jCB_provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_jCB_provinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cl_jCB_provinciaActionPerformed

    private void cl_jTF_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_jTF_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cl_jTF_ciudadActionPerformed

    private void cl_jB_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_jB_registrarActionPerformed
        // TODO add your handling code here:
        //Registrar cliente
        if(bandera)
        {
            
            Procedimientos pro = new Procedimientos();
            
            if (pro.consultarSiExiste("ruc", "cliente", cl_jTF_ruc.getText()))
            {
                JOptionPane.showMessageDialog(null, "Ya existe un usuario con ese RUC, no se registró ningún cliente");
            }
            else
            {
               String arr[] = new String[10];
               arr[0]=cl_jTF_ruc.getText();
               arr[1]=cl_jTF_nombreEmpresa.getText();
               arr[2]=cl_jTF_nombreRepresentante.getText();
               arr[3]=cl_jTF_apellidosRepresentante.getText();
               arr[4]=cl_jTF_telefono.getText();
               arr[5]=cl_jTF_telefonocelular.getText();
               arr[6]=cl_jCB_provincia.getSelectedItem().toString();
               arr[7]=cl_jTF_ciudad.getText();
               arr[8]=cl_jTF_parroquia .getText();   
               arr[9]=cl_jCB_estado.getSelectedItem().toString();
              
               String cad = "RegistroCliente";
                try {
                    Procedimientos.registro(arr,cad);
                    JOptionPane.showMessageDialog(null, "Cliente Registrado exitosamente");
                } catch (SQLException ex) {
                    Logger.getLogger(cl_registrar.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Alguno de los campos ingresados son erróneos, No se registro el cliente");
        }
    }//GEN-LAST:event_cl_jB_registrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menPrinci mp = new menPrinci();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cl_jCB_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_jCB_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cl_jCB_estadoActionPerformed

    private void cl_jTF_nombreEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cl_jTF_nombreEmpresaFocusLost
        // TODO add your handling code here:
        
        
    
        
    }//GEN-LAST:event_cl_jTF_nombreEmpresaFocusLost

    private void cl_jTF_nombreRepresentanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cl_jTF_nombreRepresentanteFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cl_jTF_nombreRepresentanteFocusLost

    private void cl_jTF_apellidosRepresentanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cl_jTF_apellidosRepresentanteFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cl_jTF_apellidosRepresentanteFocusLost

    private void cl_jTF_rucFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cl_jTF_rucFocusLost
        // TODO add your handling code here:
         
        
    }//GEN-LAST:event_cl_jTF_rucFocusLost

    private void cl_jTF_telefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cl_jTF_telefonoFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cl_jTF_telefonoFocusLost

    private void cl_jTF_telefonocelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cl_jTF_telefonocelularFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cl_jTF_telefonocelularFocusLost

    private void cl_jTF_nombreEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cl_jTF_nombreEmpresaKeyReleased
        // TODO add your handling code here:
        Funciones fun = new Funciones();
        if(evt.getKeyCode() ==KeyEvent.VK_ENTER)
        {    if (fun.validarNombreEmpresa(cl_jTF_nombreEmpresa.getText()) == false) 
            {    
                this.bandera =false;
                JOptionPane.showMessageDialog(null, "Error, nombre empresa tiene más de 50 caracteres o tiene caracteres que no son alfabéticos ");
           
            }
            else
            {
                cl_jTF_nombreRepresentante.requestFocus();
                this.bandera =true;
            }
        }
    }//GEN-LAST:event_cl_jTF_nombreEmpresaKeyReleased

    private void cl_jTF_nombreRepresentanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cl_jTF_nombreRepresentanteKeyReleased
        // TODO add your handling code here:
         Funciones fun = new Funciones();
         if(evt.getKeyCode() ==KeyEvent.VK_ENTER)
        { 
            if (fun.ValidacionNombreCaracteresYLong(cl_jTF_nombreRepresentante.getText(), 30) == false) 
            {     
                this.bandera =false;
                JOptionPane.showMessageDialog(null, "Error, nombres representante tiene más de 30 caracteres o tiene caracteres que no son alfabéticos ");
                cl_jTF_nombreRepresentante.requestFocus();
            }
            else
            {
                cl_jTF_apellidosRepresentante.requestFocus();
                this.bandera =true;
            }
        }
    }//GEN-LAST:event_cl_jTF_nombreRepresentanteKeyReleased

    private void cl_jTF_apellidosRepresentanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cl_jTF_apellidosRepresentanteKeyReleased
        // TODO add your handling code here:
         Funciones fun = new Funciones();
         if(evt.getKeyCode() ==KeyEvent.VK_ENTER)
        { 
            if (fun.ValidacionNombreCaracteresYLong(cl_jTF_apellidosRepresentante.getText(), 30)==false) 
            {
                this.bandera =false;
                JOptionPane.showMessageDialog(null, "Error, apellidos representante tiene más de 30 caracteres o tiene caracteres que no son alfabéticos ");
            
            }
            else
            {
                cl_jTF_ruc.requestFocus();
                this.bandera =true;
            }
        }
    }//GEN-LAST:event_cl_jTF_apellidosRepresentanteKeyReleased

    private void cl_jTF_rucKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cl_jTF_rucKeyReleased
        // TODO add your handling code here:
         Funciones fun = new Funciones();
        if(evt.getKeyCode() ==KeyEvent.VK_ENTER)
        { 
            if (fun.ValidacionRUC(cl_jTF_ruc.getText())== false)
            {
                this.bandera = false;
                JOptionPane.showMessageDialog(null, "Error, RUC inválido");
            
            } 
            else
            {
                cl_jTF_telefono.requestFocus();
                this.bandera =true;
            }
                
        }
    }//GEN-LAST:event_cl_jTF_rucKeyReleased

    private void cl_jTF_telefonocelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cl_jTF_telefonocelularKeyReleased
        // TODO add your handling code here:
         Funciones fun = new Funciones();
         if(evt.getKeyCode() ==KeyEvent.VK_ENTER)
        { 
            if (!fun.validarCelular(cl_jTF_telefonocelular.getText()))
            {
                this.bandera = false;
                JOptionPane.showMessageDialog(null, "Error, teléfono celular inválido");
            }
            else
            {   
                this.bandera =true; 
                cl_jCB_provincia.requestFocus();
            }
        }
    }//GEN-LAST:event_cl_jTF_telefonocelularKeyReleased

    private void cl_jTF_telefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cl_jTF_telefonoKeyReleased
        // TODO add your handling code here:
         Funciones fun = new Funciones();
        if(evt.getKeyCode() ==KeyEvent.VK_ENTER)
        { 
            if (!fun.validaFonoConv(cl_jTF_telefono.getText()))
            {
                this.bandera = false;
                JOptionPane.showMessageDialog(null, "Error, teléfono convencional inválido");
            }
            else
            {    
                cl_jTF_telefonocelular.requestFocus();
                this.bandera =true;
            }
            
        }
    }//GEN-LAST:event_cl_jTF_telefonoKeyReleased

    private void cl_jTF_ciudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cl_jTF_ciudadKeyReleased
        // TODO add your handling code here:
         Funciones fun = new Funciones();
        if(evt.getKeyCode() ==KeyEvent.VK_ENTER)
        { 
           if (!fun.nombreYLog(cl_jTF_ciudad.getText(),50))
           {
               this.bandera = false;
               JOptionPane.showMessageDialog(null, "Error, ciudad ingresada incorrecta. Contiene caracteres que no son alfabéticos o superó los 50 caracteres");
           } 
           else
           {
               cl_jTF_parroquia.requestFocus();
               this.bandera =true;
           }
        }
        
    }//GEN-LAST:event_cl_jTF_ciudadKeyReleased

    private void cl_jTF_parroquiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cl_jTF_parroquiaKeyReleased
        // TODO add your handling code here:
         Funciones fun = new Funciones();
        if(evt.getKeyCode() ==KeyEvent.VK_ENTER)
        { 
           if (!fun.nombreYLog(cl_jTF_parroquia.getText(),20))
           {
               this.bandera = false;
               JOptionPane.showMessageDialog(null, "Error, parroquia ingresada incorrecta. Contiene caracteres que no son alfabéticos o superó los 20 caracteres");
           }
           else
               this.bandera =true;
        }
    }//GEN-LAST:event_cl_jTF_parroquiaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cl_registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cl_registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cl_registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cl_registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cl_registrar(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cl_jB_registrar;
    private javax.swing.JComboBox<String> cl_jCB_estado;
    private javax.swing.JComboBox<String> cl_jCB_provincia;
    private javax.swing.JLabel cl_jL_actualizarCliente;
    private javax.swing.JLabel cl_jL_apellidoRepresentate;
    private javax.swing.JLabel cl_jL_registroCliente;
    private javax.swing.JLabel cl_jL_telefonoCelular;
    private javax.swing.JToggleButton cl_jTB_actualizar;
    private javax.swing.JTextField cl_jTF_apellidosRepresentante;
    private javax.swing.JTextField cl_jTF_ciudad;
    private javax.swing.JTextField cl_jTF_nombreEmpresa;
    private javax.swing.JTextField cl_jTF_nombreRepresentante;
    private javax.swing.JTextField cl_jTF_parroquia;
    private javax.swing.JTextField cl_jTF_ruc;
    private javax.swing.JTextField cl_jTF_telefono;
    private javax.swing.JTextField cl_jTF_telefonocelular;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
